const mowerResponses = {
	repositoryData: {
		id: 479324416,
		node_id: "R_kgDOHJHpAA",
		name: "mower",
		full_name: "alejandrososa/mower",
		private: false,
		owner: {
			login: "alejandrososa",
			id: 13384058,
			node_id: "MDQ6VXNlcjEzMzg0MDU4",
			avatar_url: "https://avatars.githubusercontent.com/u/13384058?v=4",
			gravatar_id: "",
			url: "https://api.github.com/users/alejandrososa",
			html_url: "https://github.com/alejandrososa",
			followers_url: "https://api.github.com/users/alejandrososa/followers",
			following_url: "https://api.github.com/users/alejandrososa/following{/other_user}",
			gists_url: "https://api.github.com/users/alejandrososa/gists{/gist_id}",
			starred_url: "https://api.github.com/users/alejandrososa/starred{/owner}{/repo}",
			subscriptions_url: "https://api.github.com/users/alejandrososa/subscriptions",
			organizations_url: "https://api.github.com/users/alejandrososa/orgs",
			repos_url: "https://api.github.com/users/alejandrososa/repos",
			events_url: "https://api.github.com/users/alejandrososa/events{/privacy}",
			received_events_url: "https://api.github.com/users/alejandrososa/received_events",
			type: "User",
			site_admin: false,
		},
		html_url: "https://github.com/alejandrososa/mower",
		description:
			"PHP 8, Docker, Pattern Design, PHPUnit, Symfony Components (Console, Uid, Messenger)",
		fork: false,
		url: "https://api.github.com/repos/alejandrososa/mower",
		forks_url: "https://api.github.com/repos/alejandrososa/mower/forks",
		keys_url: "https://api.github.com/repos/alejandrososa/mower/keys{/key_id}",
		collaborators_url:
			"https://api.github.com/repos/alejandrososa/mower/collaborators{/collaborator}",
		teams_url: "https://api.github.com/repos/alejandrososa/mower/teams",
		hooks_url: "https://api.github.com/repos/alejandrososa/mower/hooks",
		issue_events_url: "https://api.github.com/repos/alejandrososa/mower/issues/events{/number}",
		events_url: "https://api.github.com/repos/alejandrososa/mower/events",
		assignees_url: "https://api.github.com/repos/alejandrososa/mower/assignees{/user}",
		branches_url: "https://api.github.com/repos/alejandrososa/mower/branches{/branch}",
		tags_url: "https://api.github.com/repos/alejandrososa/mower/tags",
		blobs_url: "https://api.github.com/repos/alejandrososa/mower/git/blobs{/sha}",
		git_tags_url: "https://api.github.com/repos/alejandrososa/mower/git/tags{/sha}",
		git_refs_url: "https://api.github.com/repos/alejandrososa/mower/git/refs{/sha}",
		trees_url: "https://api.github.com/repos/alejandrososa/mower/git/trees{/sha}",
		statuses_url: "https://api.github.com/repos/alejandrososa/mower/statuses/{sha}",
		languages_url: "https://api.github.com/repos/alejandrososa/mower/languages",
		stargazers_url: "https://api.github.com/repos/alejandrososa/mower/stargazers",
		contributors_url: "https://api.github.com/repos/alejandrososa/mower/contributors",
		subscribers_url: "https://api.github.com/repos/alejandrososa/mower/subscribers",
		subscription_url: "https://api.github.com/repos/alejandrososa/mower/subscription",
		commits_url: "https://api.github.com/repos/alejandrososa/mower/commits{/sha}",
		git_commits_url: "https://api.github.com/repos/alejandrososa/mower/git/commits{/sha}",
		comments_url: "https://api.github.com/repos/alejandrososa/mower/comments{/number}",
		issue_comment_url: "https://api.github.com/repos/alejandrososa/mower/issues/comments{/number}",
		contents_url: "https://api.github.com/repos/alejandrososa/mower/contents/{+path}",
		compare_url: "https://api.github.com/repos/alejandrososa/mower/compare/{base}...{head}",
		merges_url: "https://api.github.com/repos/alejandrososa/mower/merges",
		archive_url: "https://api.github.com/repos/alejandrososa/mower/{archive_format}{/ref}",
		downloads_url: "https://api.github.com/repos/alejandrososa/mower/downloads",
		issues_url: "https://api.github.com/repos/alejandrososa/mower/issues{/number}",
		pulls_url: "https://api.github.com/repos/alejandrososa/mower/pulls{/number}",
		milestones_url: "https://api.github.com/repos/alejandrososa/mower/milestones{/number}",
		notifications_url:
			"https://api.github.com/repos/alejandrososa/mower/notifications{?since,all,participating}",
		labels_url: "https://api.github.com/repos/alejandrososa/mower/labels{/name}",
		releases_url: "https://api.github.com/repos/alejandrososa/mower/releases{/id}",
		deployments_url: "https://api.github.com/repos/alejandrososa/mower/deployments",
		created_at: "2022-04-08T09:19:24Z",
		updated_at: "2022-04-08T09:25:54Z",
		pushed_at: "2022-04-08T09:27:50Z",
		git_url: "git://github.com/alejandrososa/mower.git",
		ssh_url: "git@github.com:alejandrososa/mower.git",
		clone_url: "https://github.com/alejandrososa/mower.git",
		svn_url: "https://github.com/alejandrososa/mower",
		homepage: "",
		size: 37,
		stargazers_count: 0,
		watchers_count: 0,
		language: "PHP",
		has_issues: true,
		has_projects: true,
		has_downloads: true,
		has_wiki: true,
		has_pages: false,
		has_discussions: false,
		forks_count: 0,
		mirror_url: null,
		archived: false,
		disabled: false,
		open_issues_count: 0,
		license: null,
		allow_forking: true,
		is_template: false,
		web_commit_signoff_required: false,
		topics: [],
		visibility: "public",
		forks: 0,
		open_issues: 0,
		watchers: 0,
		default_branch: "main",
		permissions: {
			admin: true,
			maintain: true,
			push: true,
			triage: true,
			pull: true,
		},
		temp_clone_token: "",
		allow_squash_merge: true,
		allow_merge_commit: true,
		allow_rebase_merge: true,
		allow_auto_merge: false,
		delete_branch_on_merge: false,
		allow_update_branch: false,
		use_squash_pr_title_as_default: false,
		squash_merge_commit_message: "COMMIT_MESSAGES",
		squash_merge_commit_title: "COMMIT_OR_PR_TITLE",
		merge_commit_message: "PR_TITLE",
		merge_commit_title: "MERGE_MESSAGE",
		security_and_analysis: {
			secret_scanning: {
				status: "disabled",
			},
			secret_scanning_push_protection: {
				status: "disabled",
			},
		},
		network_count: 0,
		subscribers_count: 1,
	},
	pullRequest: [],
	CiStatus: {},
};
const discountsResponses = {
	repositoryData: {
		id: 477482202,
		node_id: "R_kgDOHHXM2g",
		name: "discounts",
		full_name: "alejandrososa/discounts",
		private: false,
		owner: {
			login: "alejandrososa",
			id: 13384058,
			node_id: "MDQ6VXNlcjEzMzg0MDU4",
			avatar_url: "https://avatars.githubusercontent.com/u/13384058?v=4",
			gravatar_id: "",
			url: "https://api.github.com/users/alejandrososa",
			html_url: "https://github.com/alejandrososa",
			followers_url: "https://api.github.com/users/alejandrososa/followers",
			following_url: "https://api.github.com/users/alejandrososa/following{/other_user}",
			gists_url: "https://api.github.com/users/alejandrososa/gists{/gist_id}",
			starred_url: "https://api.github.com/users/alejandrososa/starred{/owner}{/repo}",
			subscriptions_url: "https://api.github.com/users/alejandrososa/subscriptions",
			organizations_url: "https://api.github.com/users/alejandrososa/orgs",
			repos_url: "https://api.github.com/users/alejandrososa/repos",
			events_url: "https://api.github.com/users/alejandrososa/events{/privacy}",
			received_events_url: "https://api.github.com/users/alejandrososa/received_events",
			type: "User",
			site_admin: false,
		},
		html_url: "https://github.com/alejandrososa/discounts",
		description:
			"REST API endpoint that given a list of products, applies some discounts to them and can be filtered.",
		fork: false,
		url: "https://api.github.com/repos/alejandrososa/discounts",
		forks_url: "https://api.github.com/repos/alejandrososa/discounts/forks",
		keys_url: "https://api.github.com/repos/alejandrososa/discounts/keys{/key_id}",
		collaborators_url:
			"https://api.github.com/repos/alejandrososa/discounts/collaborators{/collaborator}",
		teams_url: "https://api.github.com/repos/alejandrososa/discounts/teams",
		hooks_url: "https://api.github.com/repos/alejandrososa/discounts/hooks",
		issue_events_url: "https://api.github.com/repos/alejandrososa/discounts/issues/events{/number}",
		events_url: "https://api.github.com/repos/alejandrososa/discounts/events",
		assignees_url: "https://api.github.com/repos/alejandrososa/discounts/assignees{/user}",
		branches_url: "https://api.github.com/repos/alejandrososa/discounts/branches{/branch}",
		tags_url: "https://api.github.com/repos/alejandrososa/discounts/tags",
		blobs_url: "https://api.github.com/repos/alejandrososa/discounts/git/blobs{/sha}",
		git_tags_url: "https://api.github.com/repos/alejandrososa/discounts/git/tags{/sha}",
		git_refs_url: "https://api.github.com/repos/alejandrososa/discounts/git/refs{/sha}",
		trees_url: "https://api.github.com/repos/alejandrososa/discounts/git/trees{/sha}",
		statuses_url: "https://api.github.com/repos/alejandrososa/discounts/statuses/{sha}",
		languages_url: "https://api.github.com/repos/alejandrososa/discounts/languages",
		stargazers_url: "https://api.github.com/repos/alejandrososa/discounts/stargazers",
		contributors_url: "https://api.github.com/repos/alejandrososa/discounts/contributors",
		subscribers_url: "https://api.github.com/repos/alejandrososa/discounts/subscribers",
		subscription_url: "https://api.github.com/repos/alejandrososa/discounts/subscription",
		commits_url: "https://api.github.com/repos/alejandrososa/discounts/commits{/sha}",
		git_commits_url: "https://api.github.com/repos/alejandrososa/discounts/git/commits{/sha}",
		comments_url: "https://api.github.com/repos/alejandrososa/discounts/comments{/number}",
		issue_comment_url:
			"https://api.github.com/repos/alejandrososa/discounts/issues/comments{/number}",
		contents_url: "https://api.github.com/repos/alejandrososa/discounts/contents/{+path}",
		compare_url: "https://api.github.com/repos/alejandrososa/discounts/compare/{base}...{head}",
		merges_url: "https://api.github.com/repos/alejandrososa/discounts/merges",
		archive_url: "https://api.github.com/repos/alejandrososa/discounts/{archive_format}{/ref}",
		downloads_url: "https://api.github.com/repos/alejandrososa/discounts/downloads",
		issues_url: "https://api.github.com/repos/alejandrososa/discounts/issues{/number}",
		pulls_url: "https://api.github.com/repos/alejandrososa/discounts/pulls{/number}",
		milestones_url: "https://api.github.com/repos/alejandrososa/discounts/milestones{/number}",
		notifications_url:
			"https://api.github.com/repos/alejandrososa/discounts/notifications{?since,all,participating}",
		labels_url: "https://api.github.com/repos/alejandrososa/discounts/labels{/name}",
		releases_url: "https://api.github.com/repos/alejandrososa/discounts/releases{/id}",
		deployments_url: "https://api.github.com/repos/alejandrososa/discounts/deployments",
		created_at: "2022-04-03T22:32:34Z",
		updated_at: "2022-04-03T22:34:39Z",
		pushed_at: "2022-04-04T20:40:24Z",
		git_url: "git://github.com/alejandrososa/discounts.git",
		ssh_url: "git@github.com:alejandrososa/discounts.git",
		clone_url: "https://github.com/alejandrososa/discounts.git",
		svn_url: "https://github.com/alejandrososa/discounts",
		homepage: null,
		size: 1206,
		stargazers_count: 0,
		watchers_count: 0,
		language: "PHP",
		has_issues: true,
		has_projects: true,
		has_downloads: true,
		has_wiki: true,
		has_pages: false,
		has_discussions: false,
		forks_count: 0,
		mirror_url: null,
		archived: false,
		disabled: false,
		open_issues_count: 0,
		license: null,
		allow_forking: true,
		is_template: false,
		web_commit_signoff_required: false,
		topics: [],
		visibility: "public",
		forks: 0,
		open_issues: 0,
		watchers: 0,
		default_branch: "main",
		permissions: {
			admin: true,
			maintain: true,
			push: true,
			triage: true,
			pull: true,
		},
		temp_clone_token: "",
		allow_squash_merge: true,
		allow_merge_commit: true,
		allow_rebase_merge: true,
		allow_auto_merge: false,
		delete_branch_on_merge: false,
		allow_update_branch: false,
		use_squash_pr_title_as_default: false,
		squash_merge_commit_message: "COMMIT_MESSAGES",
		squash_merge_commit_title: "COMMIT_OR_PR_TITLE",
		merge_commit_message: "PR_TITLE",
		merge_commit_title: "MERGE_MESSAGE",
		security_and_analysis: {
			secret_scanning: {
				status: "disabled",
			},
			secret_scanning_push_protection: {
				status: "disabled",
			},
		},
		network_count: 0,
		subscribers_count: 1,
	},
	pullRequest: [],
	CiStatus: {},
};
const dockboxResponses = {
	repositoryData: {
		id: 79891561,
		node_id: "MDEwOlJlcG9zaXRvcnk3OTg5MTU2MQ==",
		name: "dockbox",
		full_name: "alejandrososa/dockbox",
		private: false,
		owner: {
			login: "alejandrososa",
			id: 13384058,
			node_id: "MDQ6VXNlcjEzMzg0MDU4",
			avatar_url: "https://avatars.githubusercontent.com/u/13384058?v=4",
			gravatar_id: "",
			url: "https://api.github.com/users/alejandrososa",
			html_url: "https://github.com/alejandrososa",
			followers_url: "https://api.github.com/users/alejandrososa/followers",
			following_url: "https://api.github.com/users/alejandrososa/following{/other_user}",
			gists_url: "https://api.github.com/users/alejandrososa/gists{/gist_id}",
			starred_url: "https://api.github.com/users/alejandrososa/starred{/owner}{/repo}",
			subscriptions_url: "https://api.github.com/users/alejandrososa/subscriptions",
			organizations_url: "https://api.github.com/users/alejandrososa/orgs",
			repos_url: "https://api.github.com/users/alejandrososa/repos",
			events_url: "https://api.github.com/users/alejandrososa/events{/privacy}",
			received_events_url: "https://api.github.com/users/alejandrososa/received_events",
			type: "User",
			site_admin: false,
		},
		html_url: "https://github.com/alejandrososa/dockbox",
		description: "Entorno de desarrollo LAMP con Docker en Español ",
		fork: false,
		url: "https://api.github.com/repos/alejandrososa/dockbox",
		forks_url: "https://api.github.com/repos/alejandrososa/dockbox/forks",
		keys_url: "https://api.github.com/repos/alejandrososa/dockbox/keys{/key_id}",
		collaborators_url:
			"https://api.github.com/repos/alejandrososa/dockbox/collaborators{/collaborator}",
		teams_url: "https://api.github.com/repos/alejandrososa/dockbox/teams",
		hooks_url: "https://api.github.com/repos/alejandrososa/dockbox/hooks",
		issue_events_url: "https://api.github.com/repos/alejandrososa/dockbox/issues/events{/number}",
		events_url: "https://api.github.com/repos/alejandrososa/dockbox/events",
		assignees_url: "https://api.github.com/repos/alejandrososa/dockbox/assignees{/user}",
		branches_url: "https://api.github.com/repos/alejandrososa/dockbox/branches{/branch}",
		tags_url: "https://api.github.com/repos/alejandrososa/dockbox/tags",
		blobs_url: "https://api.github.com/repos/alejandrososa/dockbox/git/blobs{/sha}",
		git_tags_url: "https://api.github.com/repos/alejandrososa/dockbox/git/tags{/sha}",
		git_refs_url: "https://api.github.com/repos/alejandrososa/dockbox/git/refs{/sha}",
		trees_url: "https://api.github.com/repos/alejandrososa/dockbox/git/trees{/sha}",
		statuses_url: "https://api.github.com/repos/alejandrososa/dockbox/statuses/{sha}",
		languages_url: "https://api.github.com/repos/alejandrososa/dockbox/languages",
		stargazers_url: "https://api.github.com/repos/alejandrososa/dockbox/stargazers",
		contributors_url: "https://api.github.com/repos/alejandrososa/dockbox/contributors",
		subscribers_url: "https://api.github.com/repos/alejandrososa/dockbox/subscribers",
		subscription_url: "https://api.github.com/repos/alejandrososa/dockbox/subscription",
		commits_url: "https://api.github.com/repos/alejandrososa/dockbox/commits{/sha}",
		git_commits_url: "https://api.github.com/repos/alejandrososa/dockbox/git/commits{/sha}",
		comments_url: "https://api.github.com/repos/alejandrososa/dockbox/comments{/number}",
		issue_comment_url:
			"https://api.github.com/repos/alejandrososa/dockbox/issues/comments{/number}",
		contents_url: "https://api.github.com/repos/alejandrososa/dockbox/contents/{+path}",
		compare_url: "https://api.github.com/repos/alejandrososa/dockbox/compare/{base}...{head}",
		merges_url: "https://api.github.com/repos/alejandrososa/dockbox/merges",
		archive_url: "https://api.github.com/repos/alejandrososa/dockbox/{archive_format}{/ref}",
		downloads_url: "https://api.github.com/repos/alejandrososa/dockbox/downloads",
		issues_url: "https://api.github.com/repos/alejandrososa/dockbox/issues{/number}",
		pulls_url: "https://api.github.com/repos/alejandrososa/dockbox/pulls{/number}",
		milestones_url: "https://api.github.com/repos/alejandrososa/dockbox/milestones{/number}",
		notifications_url:
			"https://api.github.com/repos/alejandrososa/dockbox/notifications{?since,all,participating}",
		labels_url: "https://api.github.com/repos/alejandrososa/dockbox/labels{/name}",
		releases_url: "https://api.github.com/repos/alejandrososa/dockbox/releases{/id}",
		deployments_url: "https://api.github.com/repos/alejandrososa/dockbox/deployments",
		created_at: "2017-01-24T08:11:27Z",
		updated_at: "2022-02-07T11:08:51Z",
		pushed_at: "2017-10-27T11:58:40Z",
		git_url: "git://github.com/alejandrososa/dockbox.git",
		ssh_url: "git@github.com:alejandrososa/dockbox.git",
		clone_url: "https://github.com/alejandrososa/dockbox.git",
		svn_url: "https://github.com/alejandrososa/dockbox",
		homepage: "",
		size: 1212,
		stargazers_count: 13,
		watchers_count: 13,
		language: "Shell",
		has_issues: true,
		has_projects: true,
		has_downloads: true,
		has_wiki: true,
		has_pages: true,
		has_discussions: false,
		forks_count: 6,
		mirror_url: null,
		archived: false,
		disabled: false,
		open_issues_count: 5,
		license: {
			key: "mit",
			name: "MIT License",
			spdx_id: "MIT",
			url: "https://api.github.com/licenses/mit",
			node_id: "MDc6TGljZW5zZTEz",
		},
		allow_forking: true,
		is_template: false,
		web_commit_signoff_required: false,
		topics: [
			"apache",
			"elasticsearch",
			"laravel",
			"mariadb",
			"mongodb",
			"mysql",
			"npm",
			"nvm",
			"pgadmin",
			"php7",
			"phpmyadmin",
			"postgis",
			"postgresql",
			"react",
			"redis",
			"symfony",
			"typescript",
			"ubuntu1604",
			"webpack",
			"yii2",
		],
		visibility: "public",
		forks: 6,
		open_issues: 5,
		watchers: 13,
		default_branch: "master",
		permissions: {
			admin: true,
			maintain: true,
			push: true,
			triage: true,
			pull: true,
		},
		temp_clone_token: "",
		allow_squash_merge: true,
		allow_merge_commit: true,
		allow_rebase_merge: true,
		allow_auto_merge: false,
		delete_branch_on_merge: false,
		allow_update_branch: false,
		use_squash_pr_title_as_default: false,
		squash_merge_commit_message: "COMMIT_MESSAGES",
		squash_merge_commit_title: "COMMIT_OR_PR_TITLE",
		merge_commit_message: "PR_TITLE",
		merge_commit_title: "MERGE_MESSAGE",
		security_and_analysis: {
			secret_scanning: {
				status: "disabled",
			},
			secret_scanning_push_protection: {
				status: "disabled",
			},
		},
		network_count: 6,
		subscribers_count: 4,
	},
	pullRequest: [],
	CiStatus: {},
};

export const githubApiResponses = [mowerResponses, discountsResponses, dockboxResponses];
